spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/demo-oauth?createDatabaseIfNotExist=true
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  signing-key: 3cA3PP8L38Oh8AgMEYnrWvyCUP5y1gOIhsPGcqe6Sj8=
